FROM python:3.7

# upgrade pip3
RUN  pip3 install --upgrade pip

## TODO : Copy requirements.txt 
## and do a pip3 install -r requirements.txt

## TODO: copy qa-hf.py

## TODO: drop the user into bash shell

## TODO : to test,  within the container run
##   python  qa-hf.py